export function langCode(i18nOrCode) {
  const raw = typeof i18nOrCode === 'string' ? i18nOrCode : i18nOrCode?.language;
  return (raw || localStorage.getItem('bh_language') || 'en').split('-')[0];
}

export const L = {
  en: {
    hello: 'Hello',
    report: 'Report',
    aiReport: 'BeejHealth AI Report',
    analysisComplete: 'AI Analysis Complete',
    diseaseDetected: 'Detected',
    confidence: 'AI Confidence',
    severity: 'Severity',
    areaAffected: 'Area Affected',
    riskLevel: 'Risk Level',
    diseaseId: 'Disease Identification',
    disease: 'Disease',
    scientificName: 'Scientific name',
    localName: 'Local name',
    severityStage: 'Severity stage',
    userQuestions: 'User Questions',
    question: 'Question',
    answer: 'Answer',
    noAnswers: 'No questionnaire answers were available for this report.',
    treatmentPlan: 'Treatment Plan',
    treatmentPlan3: 'Treatment Plan - 3 Phases',
    aiTreatmentPlan: 'AI Treatment Plan',
    todayDo: 'Do Today',
    thisWeek: 'This Week',
    thisSeason: 'This Season',
    weatherRisk: 'Weather Risk',
    pdfDownload: 'PDF Download',
    reminder: 'Set Reminder',
    newDiagnosis: 'New Diagnosis',
    profile: 'My Profile',
    editProfile: 'Edit Profile',
    farmer: 'Farmer',
    expert: 'Agricultural Expert',
    verified: 'Verified',
    mobile: 'Mobile',
    email: 'Email',
    district: 'District',
    village: 'Village',
    specialization: 'Specialization',
    fee: 'Fee',
    crops: 'Crops',
    languages: 'Languages',
    notSet: 'Not set',
    profileEdit: 'Edit Profile',
    name: 'Name',
    bio: 'Bio / About',
    cancel: 'Cancel',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    activityStats: 'Activity Stats',
    consultations: 'Consultations',
    memberSince: 'Member Since',
    quickActions: 'Quick Actions',
    settings: 'Settings',
    notifications: 'Notifications',
    myFarm: 'My Farm',
    logout: 'Logout',
    todaysWeather: "Today's Weather",
    mandiPrices: 'Mandi Prices',
    seasonCost: 'This Season Cost',
    sellTime: 'right time to sell',
    loadingWeather: 'Loading weather...',
    recentConsultations: 'Recent Consultations',
    all: 'All',
    viewAllConsultations: 'See All Consultations',
    reportAction: 'Report',
    chatAction: 'Chat',
    expertAssigned: 'Expert Assigned',
    completed: 'Completed',
    pending: 'Pending',
    aiReady: 'AI Report Ready',
    confidenceWord: 'confidence',
    live: 'Live',
    msp: 'MSP',
    stable: 'Stable',
    totalCost: 'Total Cost',
    expectedYield: 'Expected Yield',
    seeds: 'Seeds',
    fertilizer: 'Fertilizer',
    medicines: 'Medicines',
    priceUp: 'price up',
    loginRequired: 'Login is required to view your consultations',
    login: 'Login',
    noConsultations: 'No consultations found',
    startFirstConsultation: 'Start your first crop consultation',
    startConsultation: 'Start Consultation',
    diagnosisHistory: 'Your plant diagnosis history',
    rate: 'Rate',
    loadingConsultations: 'Loading consultations...',
    expertDashboard: 'Expert Dashboard',
    availableNow: 'Available Now',
    busyOffline: 'Busy / Offline',
    goOffline: 'Go Offline',
    goOnline: 'Go Online',
    newCaseArrived: 'new case arrived',
    newCasesArrived: 'new cases arrived',
    see: 'See',
    caseQueue: 'Case Queue',
    allCases: 'All Cases',
    urgent: 'Urgent',
    active: 'Active',
    farmerLabel: 'Farmer',
    aiConfident: 'AI confident',
    reviewCase: 'Review Case',
    weeklyPerformance: 'This Week Performance',
    casesSolved: 'Cases Solved',
    avgResponse: 'Avg Response',
    rating: 'Rating',
    accuracy: 'Accuracy',
    repeatClients: 'Repeat Clients',
    todayAvailability: "Today's Availability",
    edit: 'Edit',
    available: 'Available',
    busy: 'Busy',
    limited: 'Limited',
    earningsSummary: 'Earnings Summary',
    today: 'Today',
    thisMonth: 'This Month',
    netPayout: 'Net Payout',
    casesWord: 'cases',
    afterDeductions: 'after deductions',
    withdrawToBank: 'Withdraw to Bank',
    minutesShort: 'min',
  },
  hi: {
    hello: 'नमस्ते',
    report: 'रिपोर्ट',
    aiReport: 'BeejHealth AI रिपोर्ट',
    analysisComplete: 'AI विश्लेषण पूरा',
    diseaseDetected: 'पाया गया',
    confidence: 'AI भरोसा',
    severity: 'गंभीरता',
    areaAffected: 'प्रभावित क्षेत्र',
    riskLevel: 'जोखिम स्तर',
    diseaseId: 'रोग पहचान',
    disease: 'रोग',
    scientificName: 'वैज्ञानिक नाम',
    localName: 'स्थानीय नाम',
    severityStage: 'गंभीरता चरण',
    userQuestions: 'यूजर सवाल',
    question: 'सवाल',
    answer: 'जवाब',
    noAnswers: 'इस रिपोर्ट के लिए सवालों के जवाब उपलब्ध नहीं हैं.',
    treatmentPlan: 'उपचार योजना',
    treatmentPlan3: 'उपचार योजना - 3 चरण',
    aiTreatmentPlan: 'AI उपचार योजना',
    todayDo: 'आज करें',
    thisWeek: 'इस हफ्ते',
    thisSeason: 'इस सीजन',
    weatherRisk: 'मौसम जोखिम',
    pdfDownload: 'PDF डाउनलोड',
    reminder: 'रिमाइंडर सेट करें',
    newDiagnosis: 'नई जांच',
    profile: 'मेरी प्रोफाइल',
    editProfile: 'प्रोफाइल संपादित करें',
    farmer: 'किसान',
    expert: 'कृषि विशेषज्ञ',
    verified: 'सत्यापित',
    mobile: 'मोबाइल',
    email: 'ईमेल',
    district: 'जिला',
    village: 'गांव',
    specialization: 'विशेषज्ञता',
    fee: 'फीस',
    crops: 'फसलें',
    languages: 'भाषाएं',
    notSet: 'सेट नहीं',
    profileEdit: 'प्रोफाइल संपादित करें',
    name: 'नाम',
    bio: 'परिचय',
    cancel: 'रद्द करें',
    saving: 'सेव हो रहा है...',
    saveChanges: 'बदलाव सेव करें',
    activityStats: 'गतिविधि आंकड़े',
    consultations: 'सलाह',
    memberSince: 'सदस्यता वर्ष',
    quickActions: 'त्वरित कार्य',
    settings: 'सेटिंग्स',
    notifications: 'सूचनाएं',
    myFarm: 'मेरा खेत',
    logout: 'लॉगआउट',
    todaysWeather: 'आज का मौसम',
    mandiPrices: 'मंडी भाव',
    seasonCost: 'इस सीजन का खर्च',
    sellTime: 'बेचने का सही समय',
    loadingWeather: 'मौसम लोड हो रहा है...',
    recentConsultations: 'हाल की सलाह',
    all: 'सब',
    viewAllConsultations: 'सभी परामर्श देखें',
    reportAction: 'रिपोर्ट',
    chatAction: 'चैट',
    expertAssigned: 'विशेषज्ञ असाइन',
    completed: 'पूरा',
    pending: 'लंबित',
    aiReady: 'AI रिपोर्ट तैयार',
    confidenceWord: 'भरोसा',
    live: 'लाइव',
    msp: 'MSP',
    stable: 'स्थिर',
    totalCost: 'कुल खर्च',
    expectedYield: 'अपेक्षित उपज',
    seeds: 'बीज',
    fertilizer: 'उर्वरक',
    medicines: 'दवाइयां',
    priceUp: 'भाव बढ़ा',
    loginRequired: 'अपनी सलाह देखने के लिए लॉगिन जरूरी है',
    login: 'लॉगिन करें',
    noConsultations: 'कोई परामर्श नहीं मिला',
    startFirstConsultation: 'पहली फसल सलाह शुरू करें',
    startConsultation: 'परामर्श शुरू करें',
    diagnosisHistory: 'आपकी पौधा जांच हिस्ट्री',
    rate: 'रेट करें',
    loadingConsultations: 'परामर्श लोड हो रहे हैं...',
    expertDashboard: 'विशेषज्ञ डैशबोर्ड',
    availableNow: 'अभी उपलब्ध',
    busyOffline: 'व्यस्त / ऑफलाइन',
    goOffline: 'ऑफलाइन जाएं',
    goOnline: 'ऑनलाइन जाएं',
    newCaseArrived: 'नया केस आया',
    newCasesArrived: 'नए केस आए',
    see: 'देखें',
    caseQueue: 'केस कतार',
    allCases: 'सभी केस',
    urgent: 'तुरंत',
    active: 'सक्रिय',
    farmerLabel: 'किसान',
    aiConfident: 'AI भरोसेमंद',
    reviewCase: 'केस देखें',
    weeklyPerformance: 'इस हफ्ते का प्रदर्शन',
    casesSolved: 'हल किए केस',
    avgResponse: 'औसत जवाब',
    rating: 'रेटिंग',
    accuracy: 'सटीकता',
    repeatClients: 'दोबारा आने वाले ग्राहक',
    todayAvailability: 'आज की उपलब्धता',
    edit: 'संपादित करें',
    available: 'उपलब्ध',
    busy: 'व्यस्त',
    limited: 'सीमित',
    earningsSummary: 'कमाई सारांश',
    today: 'आज',
    thisMonth: 'इस महीने',
    netPayout: 'नेट भुगतान',
    casesWord: 'केस',
    afterDeductions: 'कटौती के बाद',
    withdrawToBank: 'बैंक में निकालें',
    minutesShort: 'मिनट',
  },
  mr: {
    hello: 'नमस्कार',
    report: 'अहवाल',
    aiReport: 'BeejHealth AI अहवाल',
    analysisComplete: 'AI विश्लेषण पूर्ण',
    diseaseDetected: 'आढळले',
    confidence: 'AI विश्वास',
    severity: 'तीव्रता',
    areaAffected: 'प्रभावित क्षेत्र',
    riskLevel: 'जोखीम पातळी',
    diseaseId: 'रोग ओळख',
    disease: 'रोग',
    scientificName: 'वैज्ञानिक नाव',
    localName: 'स्थानिक नाव',
    severityStage: 'तीव्रता टप्पा',
    userQuestions: 'वापरकर्ता प्रश्न',
    question: 'प्रश्न',
    answer: 'उत्तर',
    noAnswers: 'या अहवालासाठी प्रश्नांची उत्तरे उपलब्ध नाहीत.',
    treatmentPlan: 'उपचार योजना',
    treatmentPlan3: 'उपचार योजना - 3 टप्पे',
    aiTreatmentPlan: 'AI उपचार योजना',
    todayDo: 'आज करा',
    thisWeek: 'या आठवड्यात',
    thisSeason: 'या हंगामात',
    weatherRisk: 'हवामान जोखीम',
    pdfDownload: 'PDF डाउनलोड',
    reminder: 'रिमाइंडर सेट करा',
    newDiagnosis: 'नवी तपासणी',
    profile: 'माझी प्रोफाइल',
    editProfile: 'प्रोफाइल संपादित करा',
    farmer: 'शेतकरी',
    expert: 'कृषी तज्ञ',
    verified: 'सत्यापित',
    mobile: 'मोबाइल',
    email: 'ईमेल',
    district: 'जिल्हा',
    village: 'गाव',
    specialization: 'विशेषज्ञता',
    fee: 'फी',
    crops: 'पिके',
    languages: 'भाषा',
    notSet: 'सेट नाही',
    profileEdit: 'प्रोफाइल संपादित करा',
    name: 'नाव',
    bio: 'परिचय',
    cancel: 'रद्द करा',
    saving: 'सेव होत आहे...',
    saveChanges: 'बदल सेव करा',
    activityStats: 'क्रियाकलाप आकडे',
    consultations: 'सल्ले',
    memberSince: 'सदस्यत्व वर्ष',
    quickActions: 'त्वरित कृती',
    settings: 'सेटिंग्ज',
    notifications: 'सूचना',
    myFarm: 'माझे शेत',
    logout: 'लॉगआउट',
    todaysWeather: 'आजचे हवामान',
    mandiPrices: 'मंडी भाव',
    seasonCost: 'या हंगामाचा खर्च',
    sellTime: 'विक्रीसाठी योग्य वेळ',
    loadingWeather: 'हवामान लोड होत आहे...',
    recentConsultations: 'अलीकडील सल्ले',
    all: 'सर्व',
    viewAllConsultations: 'सर्व सल्ले पहा',
    reportAction: 'अहवाल',
    chatAction: 'चॅट',
    expertAssigned: 'तज्ज्ञ नेमला',
    completed: 'पूर्ण',
    pending: 'प्रलंबित',
    aiReady: 'AI अहवाल तयार',
    confidenceWord: 'विश्वास',
    live: 'लाईव्ह',
    msp: 'MSP',
    stable: 'स्थिर',
    totalCost: 'एकूण खर्च',
    expectedYield: 'अपेक्षित उत्पन्न',
    seeds: 'बियाणे',
    fertilizer: 'खत',
    medicines: 'औषधे',
    priceUp: 'भाव वाढला',
    loginRequired: 'तुमचे सल्ले पाहण्यासाठी लॉगिन आवश्यक आहे',
    login: 'लॉगिन करा',
    noConsultations: 'कोणताही सल्ला सापडला नाही',
    startFirstConsultation: 'पहिला पीक सल्ला सुरू करा',
    startConsultation: 'सल्ला सुरू करा',
    diagnosisHistory: 'तुमची वनस्पती निदान हिस्ट्री',
    rate: 'रेट करा',
    loadingConsultations: 'सल्ले लोड होत आहेत...',
    expertDashboard: 'तज्ज्ञ डॅशबोर्ड',
    availableNow: 'आता उपलब्ध',
    busyOffline: 'व्यस्त / ऑफलाइन',
    goOffline: 'ऑफलाइन जा',
    goOnline: 'ऑनलाइन या',
    newCaseArrived: 'नवे केस आले',
    newCasesArrived: 'नवे केसेस आले',
    see: 'पहा',
    caseQueue: 'केस रांग',
    allCases: 'सर्व केसेस',
    urgent: 'तातडीचे',
    active: 'सक्रिय',
    farmerLabel: 'शेतकरी',
    aiConfident: 'AI विश्वास',
    reviewCase: 'केस पहा',
    weeklyPerformance: 'या आठवड्याची कामगिरी',
    casesSolved: 'सोडवलेले केसेस',
    avgResponse: 'सरासरी प्रतिसाद',
    rating: 'रेटिंग',
    accuracy: 'अचूकता',
    repeatClients: 'पुन्हा येणारे ग्राहक',
    todayAvailability: 'आजची उपलब्धता',
    edit: 'संपादित करा',
    available: 'उपलब्ध',
    busy: 'व्यस्त',
    limited: 'मर्यादित',
    earningsSummary: 'कमाई सारांश',
    today: 'आज',
    thisMonth: 'या महिन्यात',
    netPayout: 'नेट पेआउट',
    casesWord: 'केसेस',
    afterDeductions: 'कपातीनंतर',
    withdrawToBank: 'बँकेत पैसे काढा',
    minutesShort: 'मिनिटे',
  },
};

export const CROP_NAMES = {
  tomato: { en: 'Tomato', hi: 'टमाटर', mr: 'टोमॅटो' },
  wheat: { en: 'Wheat', hi: 'गेहूं', mr: 'गहू' },
  potato: { en: 'Potato', hi: 'आलू', mr: 'बटाटा' },
  cotton: { en: 'Cotton', hi: 'कपास', mr: 'कापूस' },
  corn: { en: 'Corn', hi: 'मक्का', mr: 'मका' },
  coconut: { en: 'Coconut', hi: 'नारियल', mr: 'नारळ' },
  apple: { en: 'Apple', hi: 'सेब', mr: 'सफरचंद' },
  grape: { en: 'Grape', hi: 'अंगूर', mr: 'द्राक्ष' },
  orange: { en: 'Orange', hi: 'संतरा', mr: 'संत्रे' },
  soybean: { en: 'Soybean', hi: 'सोयाबीन', mr: 'सोयाबीन' },
};

export function tx(lang, key) {
  const code = langCode(lang);
  return L[code]?.[key] || L.en[key] || key;
}

export function cropName(cropOrId, lang) {
  const rawId = typeof cropOrId === 'string' ? cropOrId : cropOrId?.id;
  const fallback = typeof cropOrId === 'string' ? cropOrId : cropOrId?.name;
  const id = CROP_NAMES[rawId]
    ? rawId
    : Object.entries(CROP_NAMES).find(([, names]) => {
      const text = String(rawId || fallback || '').toLowerCase();
      return names.en.toLowerCase() === text || text.includes(names.en.toLowerCase());
    })?.[0] || rawId;
  const code = langCode(lang);
  return CROP_NAMES[id]?.[code] || CROP_NAMES[id]?.en || fallback || '';
}

export function localeFor(lang) {
  const code = langCode(lang);
  if (code === 'hi') return 'hi-IN';
  if (code === 'mr') return 'mr-IN';
  return 'en-IN';
}

export function formatNumber(value, lang, options = {}) {
  const number = Number(value);
  if (!Number.isFinite(number)) return value;
  return new Intl.NumberFormat(localeFor(lang), options).format(number);
}

export function formatCurrency(value, lang) {
  return formatNumber(value, lang, {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  });
}

export function formatPercent(value, lang, options = {}) {
  return `${formatNumber(value, lang, options)}%`;
}

export function formatDateTime(value, lang, options = {}) {
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat(localeFor(lang), options).format(date);
}

export function localizeCropLabel(label, lang) {
  const code = langCode(lang);
  let out = String(label || '');
  Object.entries(CROP_NAMES).forEach(([id, names]) => {
    out = out.replace(new RegExp(names.en, 'gi'), names[code] || names.en);
  });
  return out;
}

export const REPORT_LABELS = {
  en: {
    aiExpertAnswers: 'AI / Expert Answers',
    savedInDb: 'Saved in DB',
    farmerUploadedPhotos: 'Farmer Uploaded Photos',
    farmerPhotoNote: 'These are the actual photos uploaded by the farmer during consultation.',
    modelResults: 'EfficientNetV2-S Model Results',
    realModel: 'Real Model',
    top3Predictions: 'Top-3 Predictions',
    hindi: 'Hindi',
    critical: 'Critical',
    high: 'High',
    mediumShort: 'Med',
    low: 'Low',
    modelBased: 'Model Based',
    sevenDaySpread: '7-Day Spread',
    affectedNow: 'Affected now',
    leaves: 'leaves',
    spotLocation: 'Spot location',
    spotColor: 'Spot color',
    status: 'Status',
    photoAnalysisComplete: 'Photo analysis complete',
    untreated: 'Untreated',
    treated: 'Treated',
    after7Days: 'after 7 days',
    in5Days: 'in 5 days',
    rootCause: 'Root Cause',
    primaryCause: 'Primary cause',
    trigger: 'Trigger',
    contributing: 'Contributing',
    risk: 'Risk',
    medicines: 'Medicines',
    aiMatched: 'AI Matched',
    best: 'Best',
    agriStore: 'Ram Agri Store - 2.3 km away',
    highRiskActToday: 'High Risk - Act Today',
    humidity: 'Humidity',
    sprayWindow: 'Spray window',
    nearbyCases: 'Nearby cases',
    expertAdvice: 'Expert Advice',
    stageBased: 'Stage based',
    consult: 'Consult',
    recommended: 'Recommended',
    expertName: 'Expert',
    followUp: 'Follow-up',
    followUpPhoto: 'Photo after 7 days',
    expertConfirm: 'Confirm with Expert',
    medicineOrder: 'Order Medicine',
    footerBrand: 'BeejHealth - Powered by FrameIQ AI',
    footerDisclaimer: 'AI-generated report for informational use only. Consult a certified agricultural expert before major treatment decisions.',
    photo: 'Photo',
  },
  hi: {
    aiExpertAnswers: 'AI / विशेषज्ञ उत्तर',
    savedInDb: 'DB में सेव',
    farmerUploadedPhotos: 'किसान द्वारा अपलोड फोटो',
    farmerPhotoNote: 'ये परामर्श के दौरान किसान द्वारा अपलोड की गई असली फोटो हैं।',
    modelResults: 'EfficientNetV2-S मॉडल परिणाम',
    realModel: 'असली मॉडल',
    top3Predictions: 'टॉप-3 अनुमान',
    hindi: 'हिंदी',
    critical: 'गंभीर',
    high: 'उच्च',
    mediumShort: 'मध्यम',
    low: 'कम',
    modelBased: 'मॉडल आधारित',
    sevenDaySpread: '7 दिन में फैलाव',
    affectedNow: 'अभी प्रभावित',
    leaves: 'पत्ते',
    spotLocation: 'दाग कहां',
    spotColor: 'दाग का रंग',
    status: 'स्थिति',
    photoAnalysisComplete: 'फोटो विश्लेषण पूरा',
    untreated: 'बिना उपचार',
    treated: 'उपचार के बाद',
    after7Days: '7 दिन बाद',
    in5Days: '5 दिन में',
    rootCause: 'मुख्य कारण',
    primaryCause: 'प्राथमिक कारण',
    trigger: 'ट्रिगर',
    contributing: 'सहायक कारण',
    risk: 'जोखिम',
    medicines: 'दवाइयां',
    aiMatched: 'AI मिलान',
    best: 'सबसे अच्छा',
    agriStore: 'राम एग्री स्टोर - 2.3 किमी दूर',
    highRiskActToday: 'उच्च जोखिम - आज कार्रवाई करें',
    humidity: 'नमी',
    sprayWindow: 'स्प्रे समय',
    nearbyCases: 'नजदीकी मामले',
    expertAdvice: 'विशेषज्ञ सलाह',
    stageBased: 'चरण आधारित',
    consult: 'परामर्श',
    recommended: 'अनुशंसित',
    expertName: 'विशेषज्ञ',
    followUp: 'फॉलो-अप',
    followUpPhoto: '7 दिन बाद फोटो',
    expertConfirm: 'विशेषज्ञ से पुष्टि करें',
    medicineOrder: 'दवा ऑर्डर करें',
    footerBrand: 'BeejHealth - FrameIQ AI द्वारा संचालित',
    footerDisclaimer: 'AI से बनी रिपोर्ट केवल जानकारी के लिए है। बड़े उपचार निर्णयों से पहले प्रमाणित कृषि विशेषज्ञ से सलाह लें।',
    photo: 'फोटो',
  },
  mr: {
    aiExpertAnswers: 'AI / तज्ज्ञ उत्तरे',
    savedInDb: 'DB मध्ये सेव',
    farmerUploadedPhotos: 'शेतकऱ्याने अपलोड केलेले फोटो',
    farmerPhotoNote: 'हे सल्लामसलतीदरम्यान शेतकऱ्याने अपलोड केलेले खरे फोटो आहेत.',
    modelResults: 'EfficientNetV2-S मॉडेल निकाल',
    realModel: 'खरे मॉडेल',
    top3Predictions: 'टॉप-3 अंदाज',
    hindi: 'हिंदी',
    critical: 'गंभीर',
    high: 'जास्त',
    mediumShort: 'मध्यम',
    low: 'कमी',
    modelBased: 'मॉडेल आधारित',
    sevenDaySpread: '7 दिवसांत प्रसार',
    affectedNow: 'सध्या प्रभावित',
    leaves: 'पाने',
    spotLocation: 'डाग कुठे',
    spotColor: 'डागाचा रंग',
    status: 'स्थिती',
    photoAnalysisComplete: 'फोटो विश्लेषण पूर्ण',
    untreated: 'उपचाराशिवाय',
    treated: 'उपचारानंतर',
    after7Days: '7 दिवसांनी',
    in5Days: '5 दिवसांत',
    rootCause: 'मूळ कारण',
    primaryCause: 'प्राथमिक कारण',
    trigger: 'कारण',
    contributing: 'सहाय्यक कारण',
    risk: 'जोखीम',
    medicines: 'औषधे',
    aiMatched: 'AI जुळले',
    best: 'सर्वोत्तम',
    agriStore: 'राम अॅग्री स्टोर - 2.3 किमी दूर',
    highRiskActToday: 'जास्त जोखीम - आजच कृती करा',
    humidity: 'आर्द्रता',
    sprayWindow: 'फवारणी वेळ',
    nearbyCases: 'जवळची प्रकरणे',
    expertAdvice: 'तज्ज्ञ सल्ला',
    stageBased: 'टप्प्यावर आधारित',
    consult: 'सल्ला',
    recommended: 'शिफारस केलेले',
    expertName: 'तज्ज्ञ',
    followUp: 'फॉलो-अप',
    followUpPhoto: '7 दिवसांनी फोटो',
    expertConfirm: 'तज्ज्ञाकडून पुष्टी करा',
    medicineOrder: 'औषध ऑर्डर करा',
    footerBrand: 'BeejHealth - FrameIQ AI द्वारे समर्थित',
    footerDisclaimer: 'AI-निर्मित अहवाल फक्त माहितीसाठी आहे. मोठे उपचार निर्णय घेण्यापूर्वी प्रमाणित कृषी तज्ज्ञांचा सल्ला घ्या.',
    photo: 'फोटो',
  },
};

const REPORT_VALUE_TRANSLATIONS = {
  en: {
    'Aagat Jhulsa Rog': 'Early blight disease',
    'Naariyal Patta Dhabb Rog': 'Coconut leaf spot disease',
    'Naariyal Bhoora Patta Rog': 'Coconut brown leaf spot disease',
    'Stage 2/5 — Moderate': 'Stage 2/5 - Moderate',
    'Stage 1/5 — Early': 'Stage 1/5 - Early',
    'Stage 3/5 — High': 'Stage 3/5 - High',
    'Stage 3/5 — Moderate-High': 'Stage 3/5 - Moderate-High',
    'High humidity + baarish pichle hafte': 'High humidity and rain last week',
    '3rd consecutive season — same variety': '3rd consecutive season - same variety',
    'Affected patte hatao. Spray band karo. Waterlogging check karo.': 'Remove affected leaves. Pause spraying. Check for waterlogging.',
    'Mancozeb 75% WP — 2.5g/L spray, 2x in 7 days. Poori fasal cover karein.': 'Spray Mancozeb 75% WP at 2.5 g/L, twice in 7 days. Cover the full crop.',
    'Crop rotation karein. Resistant variety use karein. Soil health maintain karein.': 'Use crop rotation, resistant varieties, and maintain soil health.',
    'Baarish + humidity 68–75%': 'Rain + humidity 68-75%',
    'Dry conditions — monitoring needed': 'Dry conditions - monitoring needed',
    'Spray nahi kiya tha lamba time': 'No spray was done for a long time',
    'Recent spray tha — phir bhi infection': 'Recent spray was done, but infection still appeared',
    'Aaj 4–6 PM': 'Today 4-6 PM',
    'Neeche ke patte': 'Lower leaves',
    'Bhoora / Brown': 'Brown',
    'Early blight on lower leaves — spreading rapidly': 'Early blight on lower leaves - spreading rapidly',
    'Nitrogen deficiency — yellowing of leaves': 'Nitrogen deficiency - yellowing of leaves',
    'Leaf wilting and stem discoloration': 'Leaf wilting and stem discoloration',
    'Late Blight risk — brown spots visible': 'Late blight risk - brown spots visible',
  },
  hi: {
    'Early Blight': 'अगेती झुलसा',
    'Gray Leaf Spot': 'ग्रे लीफ स्पॉट',
    'Leaf Rust': 'पत्ती का रतुआ',
    'Late Blight': 'पछेती झुलसा',
    'Bacterial Blight': 'बैक्टीरियल झुलसा',
    'Powdery Mildew': 'चूर्णिल आसिता',
    'Aagat Jhulsa Rog': 'अगेती झुलसा रोग',
    'Naariyal Patta Dhabb Rog': 'नारियल पत्ता धब्बा रोग',
    'Naariyal Bhoora Patta Rog': 'नारियल भूरा पत्ता रोग',
    'Stage 2/5 — Moderate': 'चरण 2/5 - मध्यम',
    'Stage 1/5 — Early': 'चरण 1/5 - शुरुआती',
    'Stage 3/5 — High': 'चरण 3/5 - उच्च',
    'Stage 3/5 — Moderate-High': 'चरण 3/5 - मध्यम-उच्च',
    'Fungal infection — Alternaria solani': 'फंगल संक्रमण - Alternaria solani',
    'High humidity + baarish pichle hafte': 'पिछले सप्ताह अधिक नमी और बारिश',
    '3rd consecutive season — same variety': 'लगातार तीसरा सीजन - वही किस्म',
    'Affected patte hatao. Spray band karo. Waterlogging check karo.': 'प्रभावित पत्ते हटाएं। अभी स्प्रे रोकें। पानी भराव जांचें।',
    'Mancozeb 75% WP — 2.5g/L spray, 2x in 7 days. Poori fasal cover karein.': 'Mancozeb 75% WP - 2.5 ग्राम/लीटर स्प्रे करें, 7 दिनों में 2 बार। पूरी फसल कवर करें।',
    'Crop rotation karein. Resistant variety use karein. Soil health maintain karein.': 'फसल चक्र अपनाएं। रोग-रोधी किस्म लगाएं। मिट्टी की सेहत बनाए रखें।',
    'Chemical Fungicide': 'रासायनिक फफूंदनाशक',
    'Preventive Fungicide': 'रोकथाम फफूंदनाशक',
    'Organic Option': 'जैविक विकल्प',
    'Baarish + humidity 68–75%': 'बारिश + नमी 68-75%',
    'Dry conditions — monitoring needed': 'सूखी स्थिति - निगरानी जरूरी',
    'Spray nahi kiya tha lamba time': 'लंबे समय से स्प्रे नहीं किया था',
    'Recent spray tha — phir bhi infection': 'हाल में स्प्रे हुआ था - फिर भी संक्रमण',
    '68–75% Dangerous': '68-75% खतरनाक',
    'Aaj 4–6 PM': 'आज शाम 4-6 बजे',
    '8 within 5km': '5 किमी में 8 मामले',
    'Neeche ke patte': 'नीचे के पत्ते',
    'Bhoora / Brown': 'भूरा',
    'Early blight on lower leaves — spreading rapidly': 'नीचे के पत्तों पर अगेती झुलसा - तेजी से फैल रहा है',
    'Nitrogen deficiency — yellowing of leaves': 'नाइट्रोजन की कमी - पत्ते पीले हो रहे हैं',
    'Leaf wilting and stem discoloration': 'पत्ते मुरझाना और तने का रंग बदलना',
    'Late Blight risk — brown spots visible': 'पछेती झुलसा का जोखिम - भूरे धब्बे दिख रहे हैं',
    'medium': 'मध्यम',
    'high': 'उच्च',
    'critical': 'गंभीर',
    'low': 'कम',
  },
  mr: {
    'Early Blight': 'अर्ली ब्लाइट',
    'Gray Leaf Spot': 'ग्रे लीफ स्पॉट',
    'Leaf Rust': 'पानावरील तांबेरा',
    'Late Blight': 'लेट ब्लाइट',
    'Bacterial Blight': 'जिवाणूजन्य करपा',
    'Powdery Mildew': 'भुरी रोग',
    'Aagat Jhulsa Rog': 'अर्ली ब्लाइट रोग',
    'Naariyal Patta Dhabb Rog': 'नारळ पान ठिपका रोग',
    'Naariyal Bhoora Patta Rog': 'नारळ तपकिरी पान रोग',
    'Stage 2/5 — Moderate': 'टप्पा 2/5 - मध्यम',
    'Stage 1/5 — Early': 'टप्पा 1/5 - सुरुवातीचा',
    'Stage 3/5 — High': 'टप्पा 3/5 - जास्त',
    'Stage 3/5 — Moderate-High': 'टप्पा 3/5 - मध्यम-जास्त',
    'Fungal infection — Alternaria solani': 'बुरशीजन्य संसर्ग - Alternaria solani',
    'High humidity + baarish pichle hafte': 'मागील आठवड्यात जास्त आर्द्रता आणि पाऊस',
    '3rd consecutive season — same variety': 'सलग तिसरा हंगाम - तीच जात',
    'Affected patte hatao. Spray band karo. Waterlogging check karo.': 'प्रभावित पाने काढा. सध्या फवारणी थांबवा. पाणी साचते का ते तपासा.',
    'Mancozeb 75% WP — 2.5g/L spray, 2x in 7 days. Poori fasal cover karein.': 'Mancozeb 75% WP - 2.5 ग्रॅम/लीटर फवारणी करा, 7 दिवसांत 2 वेळा. संपूर्ण पीक झाका.',
    'Crop rotation karein. Resistant variety use karein. Soil health maintain karein.': 'पीक फेरपालट करा. रोगप्रतिकारक जात वापरा. मातीचे आरोग्य राखा.',
    'Chemical Fungicide': 'रासायनिक बुरशीनाशक',
    'Preventive Fungicide': 'प्रतिबंधक बुरशीनाशक',
    'Organic Option': 'सेंद्रिय पर्याय',
    'Baarish + humidity 68–75%': 'पाऊस + आर्द्रता 68-75%',
    'Dry conditions — monitoring needed': 'कोरडी स्थिती - निरीक्षण गरजेचे',
    'Spray nahi kiya tha lamba time': 'बराच काळ फवारणी केलेली नव्हती',
    'Recent spray tha — phir bhi infection': 'अलीकडे फवारणी झाली - तरीही संसर्ग',
    '68–75% Dangerous': '68-75% धोकादायक',
    'Aaj 4–6 PM': 'आज संध्याकाळी 4-6',
    '8 within 5km': '5 किमीमध्ये 8 प्रकरणे',
    'Neeche ke patte': 'खालची पाने',
    'Bhoora / Brown': 'तपकिरी',
    'Early blight on lower leaves — spreading rapidly': 'खालच्या पानांवर अर्ली ब्लाइट - वेगाने पसरत आहे',
    'Nitrogen deficiency — yellowing of leaves': 'नायट्रोजन कमतरता - पाने पिवळी पडत आहेत',
    'Leaf wilting and stem discoloration': 'पाने कोमेजणे आणि खोडाचा रंग बदलणे',
    'Late Blight risk — brown spots visible': 'लेट ब्लाइटचा धोका - तपकिरी डाग दिसत आहेत',
    'medium': 'मध्यम',
    'high': 'जास्त',
    'critical': 'गंभीर',
    'low': 'कमी',
  },
};

const REPORT_LABEL_ALIASES = {
  'Top prediction': 'topPrediction',
  Diagnosis: 'diagnosis',
  'Scientific name': 'scientificName',
  'Primary cause': 'primaryCause',
  'Immediate action': 'immediateAction',
  'This season': 'thisSeason',
  'AI treatment plan': 'aiTreatmentPlan',
  Urgency: 'urgency',
};

const REPORT_EXTRA_LABELS = {
  en: {
    topPrediction: 'Top prediction',
    diagnosis: 'Diagnosis',
    immediateAction: 'Immediate action',
    urgency: 'Urgency',
  },
  hi: {
    topPrediction: 'मुख्य अनुमान',
    diagnosis: 'निदान',
    immediateAction: 'तुरंत कार्रवाई',
    urgency: 'तात्कालिकता',
  },
  mr: {
    topPrediction: 'मुख्य अंदाज',
    diagnosis: 'निदान',
    immediateAction: 'तातडीची कृती',
    urgency: 'तातडी',
  },
};

export function rt(lang, key) {
  const code = langCode(lang);
  return REPORT_LABELS[code]?.[key] || REPORT_LABELS.en[key] || tx(lang, key);
}

export function reportLabel(label, lang) {
  const key = REPORT_LABEL_ALIASES[label] || label;
  const code = langCode(lang);
  return REPORT_EXTRA_LABELS[code]?.[key] || REPORT_LABELS[code]?.[key] || tx(lang, key) || label;
}

export function reportValue(value, lang) {
  if (value === null || value === undefined) return value;
  const code = langCode(lang);
  const text = String(value);
  const translated = REPORT_VALUE_TRANSLATIONS[code]?.[text];
  if (translated) return translated;
  return text;
}
